<?php
/**
 * Author: ddinnnng@qq.com
 * Date: 2016/7/27
 * Description:
 */
namespace Ddinnnng\Singleton;

abstract class Factory extends FactoryAbstract {

    final public static function getInstance()
    {
        return parent::getInstance(); // TODO: Change the autogenerated stub
    }

    final public static function removeInstance()
    {
        parent::removeInstance(); // TODO: Change the autogenerated stub
    }

}